spring:
  application:
    name: gymapp
  profiles:
    group:
      local: secrets
      dev: secrets
      stg: secrets
      prod: secrets

application:
  security:
    defaultPasswordLength: 10
    userBlock:
      maxLoginAttempts: 3
      durationSeconds: 300
    accessToken:
      issuer: localhost
      lifetimeSeconds: 600
    refreshToken:
      lifetimeSeconds: 864000
      lengthBytes: 32
    cors:
      allowedOrigins: []

logging:
  pattern:
    level: "%5p [%X{transactionId}]"
