logging:
  threshold:
    console: trace
  level:
    root: info
    org.springframework: trace
    com.epam.lenda: trace

spring:
  datasource:
    url: jdbc:postgresql://${application.db.host}:${application.db.port}/${application.db.name}
    driver-class-name: org.postgresql.Driver
    username: ${application.db.username}
    password: ${application.db.password}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    key:
      enabled: db,diskspace
