spring:
  application:
    name: report-service
  activemq:
    broker-url: ${ACTIVEMQ_BROKER_URL:tcp://localhost:61616}
    user: ${ACTIVEMQ_CONNECTION_USER:system}
    password: ${ACTIVEMQ_CONNECTION_PASSWORD:manager}
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/gymapp-report}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://main-service:8082

server:
  port: 8081

logging:
  pattern:
    level: "%5p [%X{transactionId}]"
  threshold:
    console: trace
  level:
    root: info
    org.springframework: trace
    com.epam.lenda: trace

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    key:
      enabled: db,diskspace

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    preferIpAddress: true
